### ISSUE TITLE
Error with certain checkpoints

### ISSUE THREAD

**Issue by brucethemoose** [Akegarasu/sd-model-converter#1]
An example of a model that fails:

https://civitai.com/models/1315/seekart-mega

```
C:\Users\Alpha\clone\sd-model-converter>python convert.py --f "F:\AIModels\Stable-diffusion\seekArtMega_v1Safetensors.safetensors" --full --fp16 --safe-tensors
Traceback (most recent call last):
  File "C:\Users\Alpha\clone\sd-model-converter\convert.py", line 41, in <module>
    converted = convert(cmds.f, cmds.fp16, not cmds.full)
  File "C:\Users\Alpha\clone\sd-model-converter\convert.py", line 13, in convert
    m = torch.load(path, map_location="cpu")
  File "F:\InstalledPrograms\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "F:\InstalledPrograms\lib\site-packages\torch\serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x1a'.
 ```

**Comment by brucethemoose** [comment]
Oh, `x1a` is an escape character. Thats definitely not a coincidence. 

I will see if this is a windows only issue later.

**Comment by Akegarasu** [comment]
It's a bug. This script is designed for reading from **torch models** not safetensors, I will fix it later.

**Comment by Akegarasu** [comment]
fixed.
